In [6]:
import pandas as pd
df = pd.read_csv('C:\\Users\\e3027859\\Most-Recent-Cohorts-Scorecard-Elements.csv', index_col=0)
df.head()

,OPEID,OPEID6,INSTNM,CITY,STABBR,INSTURL,NPCURL,HCM2,PREDDEG,HIGHDEG,...,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GT_25K_P6,GT_28K_P6,GRAD_DEBT_MDN_SUPP,GRAD_DEBT_MDN10YR_SUPP,RPY_3YR_RT_SUPP,C150_L4_POOLED_SUPP,C150_4_POOLED_SUPP
UNITID,,,,,,,,,,,,,,,,,,,,,
100654,100200,1002,Alabama A & M University,Normal,AL,www.aamu.edu/,www2.aamu.edu/scripts/netpricecalc/npcalc.htm,0,3,4,...,0.7667,0.0859,31000,0.453,0.431,32750,348.16551225731,0.2531554273,NaN,0.2913
100663,105200,1052,University of Alabama at Birmingham,Birmingham,AL,www.uab.edu,uab.studentaidcalculator.com/survey.aspx,0,3,4,...,0.5179,0.2363,41200,0.669,0.631,21833,232.106797835537,0.513963161,NaN,0.5384
100690,2503400,25034,Amridge University,Montgomery,AL,www.amridgeuniversity.edu,www2.amridgeuniversity.edu:9091/,0,3,4,...,0.8436,0.8571,39600,0.658,0.542,22890,243.343773299842,0.2307692308,NaN,PrivacySuppressed
100706,105500,1055,University of Alabama in Huntsville,Huntsville,AL,www.uah.edu,finaid.uah.edu/,0,3,4,...,0.4312,0.2255,46700,0.685,0.649,22647,240.760438353933,0.5485090298,NaN,0.4905
100724,100500,1005,Alabama State University,Montgomery,AL,www.alasu.edu,www.alasu.edu/cost-aid/forms/calculator/index....,0,3,4,...,0.8113,0.0974,27700,0.393,0.351,31500,334.876752247489,0.2185867473,NaN,0.2475

In [7]:
df.count

<bound method DataFrame.count of              OPEID  OPEID6                                             INSTNM  \
UNITID
100654      100200    1002                           Alabama A & M University
100663      105200    1052                University of Alabama at Birmingham
100690     2503400   25034                                 Amridge University
100706      105500    1055                University of Alabama in Huntsville
100724      100500    1005                           Alabama State University
100751      105100    1051                          The University of Alabama
100760      100700    1007                  Central Alabama Community College
100812      100800    1008                            Athens State University
100830      831000    8310                    Auburn University at Montgomery
100858      100900    1009                                  Auburn University
100937      101200    1012                        Birmingham Southern College
101028     1218200   12182             Chattahoochee Valley Community College
101073     1055400   10554                          Concordia College Alabama
101116     1303906   13039                        South University-Montgomery
101143      101500    1015                 Enterprise State Community College
101161      106000    1060                  Coastal Alabama Community College
101189      100300    1003                                Faulkner University
101240      101700    1017                    Gadsden State Community College
101277     4187200   41872               New Beginning College of Cosmetology
101286      101800    1018          George C Wallace Community College-Dothan
101295      787100    7871  George C Wallace State Community College-Hance...
101301      569900    5699     George C Wallace State Community College-Selma
101365      962107    9621                      Herzing University-Birmingham
101435      101900    1019                                 Huntingdon College
101453     2199700   21997                      Heritage Christian University
101462      526000    5260  J. F. Drake State Community and Technical College
101471     3002500   30025                 J F Ingram State Technical College
101480      102000    1020                      Jacksonville State University
101499      102100    1021                  Jefferson Davis Community College
101505      102200    1022                  Jefferson State Community College
...            ...     ...                                                ...
45897302    145992    1459                            Strayer University-Katy
45897303    145994    1459               Strayer University-Northwest Houston
45897304    145995    1459                           Strayer University-Plano
45897305  10145900    1459                      Strayer University-Cedar Hill
45897306  10145901    1459                    Strayer University-North Dallas
45897307  10145908    1459                     Strayer University-San Antonio
45897308  10145909    1459                        Strayer University-Stafford
45920401   4169701   41697                                     Unitek College
47503301   4208601   42086        Relay Graduate School of Education - Newark
47503302   4208602   42086   Relay Graduate School of Education - New Orleans
47503303   4208605   42086      Relay Graduate School of Education - Delaware
47503304   4208606   42086       Relay Graduate School of Education - Memphis
47503305   4208603   42086       Relay Graduate School of Education - Houston
47503306   4208604   42086       Relay Graduate School of Education - Chicago
47503307   4208607   42086   Relay Graduate School of Education - Baton Rouge
47503308   4208608   42086  Relay Graduate School of Education - Philadelp...
47503309   4208609   42086        Relay Graduate School of Education - Denver
47503310   4208610   42086     Relay Graduate School of Education - Nashville
47647001   4088301   40883                           WestMed College - Merced
47657701   4184801   41848                                    Vantage College
47657702   4184802   41848                                    Vantage College
47662901   4189101   41891                  Salon Institute - Columbus Campus
47691101   4205801   42058          SAE Institute of Technology San Francisco
48065701    869423    8694                  Rasmussen College - Overland Park
48154401   4220901   42209  National Personal Training Institute of Cleveland
48305401   4224601   42246             Barber School of Pittsburgh - Ambridge
48387801   4223701   42237  Bay Area Medical Academy - San Jose Satellite ...
48400201   4228101   42281                        High Desert Medical College
48414501   4232401   42324                        Vantage College-San Antonio
48778201   4221501   42215                                       BCI - Malden

                      CITY STABBR  \
UNITID
100654              Normal     AL
100663          Birmingham     AL
100690          Montgomery     AL
100706          Huntsville     AL
100724          Montgomery     AL
100751          Tuscaloosa     AL
100760      Alexander City     AL
100812              Athens     AL
100830          Montgomery     AL
100858              Auburn     AL
100937          Birmingham     AL
101028         Phenix City     AL
101073               Selma     AL
101116          Montgomery     AL
101143          Enterprise     AL
101161         Bay Minette     AL
101189          Montgomery     AL
101240             Gadsden     AL
101277         Albertville     AL
101286              Dothan     AL
101295          Hanceville     AL
101301               Selma     AL
101365          Birmingham     AL
101435          Montgomery     AL
101453            Florence     AL
101462          Huntsville     AL
101471          Deatsville     AL
101480        Jacksonville     AL
101499             Brewton     AL
101505          Birmingham     AL
...                    ...    ...
45897302           Houston     TX
45897303           Houston     TX
45897304             Plano     TX
45897305        Cedar Hill     TX
45897306            Dallas     TX
45897307       San Antonio     TX
45897308          Stafford     TX
45920401           Fremont     CA
47503301            Newark     NJ
47503302       New Orleans     LA
47503303        Wilmington     DE
47503304           Memphis     TN
47503305           Houston     TX
47503306           Chicago     IL
47503307       Baton Rouge     LA
47503308      Philadelphia     PA
47503309            Denver     CO
47503310         Nashville     TN
47647001            Merced     CA
47657701           El Paso     TX
47657702            Austin     TX
47662901      Lewis Center     OH
47691101        Emeryville     CA
48065701     Overland Park     KS
48154401  Highland Heights     OH
48305401          Ambridge     PA
48387801          San Jose     CA
48400201         Lancaster     CA
48414501       San Antonio     TX
48778201            Malden     MA

                                                    INSTURL  \
UNITID
100654                                        www.aamu.edu/
100663                                          www.uab.edu
100690                            www.amridgeuniversity.edu
100706                                          www.uah.edu
100724                                        www.alasu.edu
100751                                          www.ua.edu/
100760                                         www.cacc.edu
100812                                       www.athens.edu
100830                                          www.aum.edu
100858                                       www.auburn.edu
100937                                         www.bsc.edu/
101028                                           www.cv.edu
101073                                        www.ccal.edu/
101116    www.southuniversity.edu/montgomery#location=Mo...
101143                                         www.escc.edu
101161                               www.coastalalabama.edu
101189                                     www.faulkner.edu
101240                                 www.gadsdenstate.edu
101277                               www.nbccosmetology.com
101286                                      www.wallace.edu
101295                                 www.wallacestate.edu
101301                                         www.wccs.edu
101365                                     www.herzing.edu/
101435                                   www.huntingdon.edu
101453                                          www.hcu.edu
101462                                   www.drakestate.edu
101471                                         www.istc.edu
101480                                         www.jsu.edu/
101499                               www.coastalalabama.edu
101505                              www.jeffersonstate.edu/
...                                                     ...
45897302                         www.strayer.edu/texas/katy
45897303            www.strayer.edu/texas/northwest-houston
45897304                        www.strayer.edu/texas/plano
45897305                   www.strayer.edu/texas/cedar-hill
45897306                 www.strayer.edu/texas/north-dallas
45897307                  www.strayer.edu/texas/san-antonio
45897308                     www.strayer.edu/texas/stafford
45920401                             www.unitekcollege.edu/
47503301                    relay.edu/location/relay-newark
47503302               relay.edu/location/relay-new-orleans
47503303                  relay.edu/location/relay-delaware
47503304                   relay.edu/location/relay-memphis
47503305                   relay.edu/location/relay-houston
47503306                   relay.edu/location/relay-chicago
47503307               relay.edu/location/relay-baton-rouge
47503308       relay.edu/location/relay-philadelphia-camden
47503309                    relay.edu/location/relay-denver
47503310                 relay.edu/location/relay-nashville
47647001                             www.westmedcollege.edu
47657701                                    www.vantage.edu
47657702                                    www.vantage.edu
47662901                             www.saloninstitute.edu
47691101                                        usa.sae.edu
48065701                                      rasmussen.edu
48154401                                       nptiohio.edu
48305401                                        www.bsp.edu
48387801                                    www.bamasf.com/
48400201                                       www.hdmc.edu
48414501                                    www.vantage.edu
48778201                                   bostoncareer.org

                                                     NPCURL  HCM2  PREDDEG  \
UNITID
100654        www2.aamu.edu/scripts/netpricecalc/npcalc.htm     0        3
100663             uab.studentaidcalculator.com/survey.aspx     0        3
100690                     www2.amridgeuniversity.edu:9091/     0        3
100706                                      finaid.uah.edu/     0        3
100724    www.alasu.edu/cost-aid/forms/calculator/index....     0        3
100751            financialaid.ua.edu/net-price-calculator/     0        3
100760    www.cacc.edu/NetPriceCalculator/14-15/npcalc.html     0        2
100812    https://24.athens.edu/apex/prod8/f?p=174:1:394...     0        3
100830    www.aum.edu/current-students/financial-informa...     0        3
100858    https://www.auburn.edu/admissions/netpricecalc...     0        3
100937                     www.bsc.edu/fp/np-calculator.cfm     0        3
101028       https://www.cv.edu/about/consumer-information/     0        2
101073      www.ccal.edu/admissions/net-pricing-calculator/     0        3
101116    tcc.noellevitz.com/edmc/South Net Price Calcul...     0        3
101143             https://www.escc.edu/netprice/npcalc.htm     0        2
101161                               www.coastalalabama.edu     0        2
101189          www.faulkner.edu/net-price-calculator-form/     0        3
101240            www.gadsdenstate.edu/net-price-calculator     0        1
101277                   nbccosmetology.com/sa/nbc_zonemap/     0        1
101286            www.wallace.edu/net_price_calculator.aspx     0        2
101295    www.wallacestate.edu/Financial-Aid/Net-Price-C...     0        2
101301     www.wccs.edu/financial-aid/net-price-calculator/     0        2
101365    www.herzing.edu/financial-aid/net-price-calcul...     0        1
101435    hawk.huntingdon.edu/oiac/netpricecalculator/np...     0        3
101453                      www.hcu.edu/netpricecalculator/     0        3
101462    www.drakestate.edu/admissions/net_price_calcul...     0        1
101471      nces.ed.gov/ipeds/netpricecalculator/Npc_2.aspx     0        1
101480                                  www.jsu.edu/finaid/     0        3
101499                               www.coastalalabama.edu     0        2
101505    www.jeffersonstate.edu/financial-aid/net-price...     0        2
...                                                     ...   ...      ...
45897302                                                NaN     0        0
45897303                                                NaN     0        0
45897304                                                NaN     0        0
45897305                                                NaN     0        0
45897306                                                NaN     0        0
45897307                                                NaN     0        0
45897308                                                NaN     0        0
45920401                                                NaN     0        0
47503301                                                NaN     0        0
47503302                                                NaN     0        0
47503303                                                NaN     0        0
47503304                                                NaN     0        0
47503305                                                NaN     0        0
47503306                                                NaN     0        0
47503307                                                NaN     0        0
47503308                                                NaN     0        0
47503309                                                NaN     0        0
47503310                                                NaN     0        0
47647001                                                NaN     0        0
47657701                                                NaN     0        0
47657702                                                NaN     0        0
47662901                                                NaN     0        0
47691101                                                NaN     0        0
48065701                                                NaN     0        0
48154401                                                NaN     0        0
48305401                                                NaN     0        0
48387801                                                NaN     0        0
48400201                                                NaN     0        0
48414501                                                NaN     0        0
48778201                                                NaN     0        0

          HIGHDEG         ...          PCTFLOAN  UG25ABV    MD_EARN_WNE_P10  \
UNITID                    ...
100654          4         ...            0.7667   0.0859              31000
100663          4         ...            0.5179   0.2363              41200
100690          4         ...            0.8436   0.8571              39600
100706          4         ...            0.4312   0.2255              46700
100724          4         ...            0.8113   0.0974              27700
100751          4         ...            0.4007   0.0810              44500
100760          2         ...            0.3234   0.2630              27700
100812          3         ...            0.6455   0.6774              38700
100830          4         ...            0.5565   0.2257              33300
100858          4         ...            0.3280   0.0427              48800
100937          3         ...            0.4729   0.0141              46700
101028          2         ...            0.2697   0.3604              28900
101073          3         ...            0.8830   0.1294              20600
101116          4         ...            0.7087   0.6109              33400
101143          2         ...            0.1738   0.2896              31800
101161          2         ...            0.4779   0.2598              29100
101189          4         ...            0.6954   0.4353              35400
101240          2         ...            0.0000   0.3320              26700
101277          1         ...            0.4545   0.2747                NaN
101286          2         ...            0.0000   0.3422              24700
101295          2         ...            0.3330   0.2671              32200
101301          2         ...            0.0000   0.2753              23300
101365          4         ...            0.7083   0.7147              37800
101435          3         ...            0.7093   0.2196              39900
101453          4         ...            0.2586   0.5862  PrivacySuppressed
101462          2         ...            0.0000   0.4769              23800
101471          1         ...            0.0000      NaN                NaN
101480          4         ...            0.6435   0.1814              35800
101499          2         ...            0.0000   0.3843              26200
101505          2         ...            0.1784   0.3118              30600
...           ...         ...               ...      ...                ...
45897302        0         ...               NaN      NaN              45900
45897303        0         ...               NaN      NaN              45900
45897304        0         ...               NaN      NaN              45900
45897305        0         ...               NaN      NaN              45900
45897306        0         ...               NaN      NaN              45900
45897307        0         ...               NaN      NaN              45900
45897308        0         ...               NaN      NaN              45900
45920401        0         ...               NaN      NaN  PrivacySuppressed
47503301        0         ...               NaN      NaN                NaN
47503302        0         ...               NaN      NaN                NaN
47503303        0         ...               NaN      NaN                NaN
47503304        0         ...               NaN      NaN                NaN
47503305        0         ...               NaN      NaN                NaN
47503306        0         ...               NaN      NaN                NaN
47503307        0         ...               NaN      NaN                NaN
47503308        0         ...               NaN      NaN                NaN
47503309        0         ...               NaN      NaN                NaN
47503310        0         ...               NaN      NaN                NaN
47647001        0         ...               NaN      NaN                NaN
47657701        0         ...               NaN      NaN                NaN
47657702        0         ...               NaN      NaN                NaN
47662901        0         ...               NaN      NaN                NaN
47691101        0         ...               NaN      NaN                NaN
48065701        0         ...               NaN      NaN              32600
48154401        0         ...               NaN      NaN                NaN
48305401        0         ...               NaN      NaN                NaN
48387801        0         ...               NaN      NaN                NaN
48400201        0         ...               NaN      NaN                NaN

In [13]:
df['CITY'].head()

UNITID
100654        Normal
100663    Birmingham
100690    Montgomery
100706    Huntsville
100724    Montgomery
Name: CITY, dtype: object

In [17]:
college_race = df.loc[:, 'OPEID':'CITY']
college_race.head()

          OPEID  OPEID6                               INSTNM        CITY
UNITID
100654   100200    1002             Alabama A & M University      Normal
100663   105200    1052  University of Alabama at Birmingham  Birmingham
100690  2503400   25034                   Amridge University  Montgomery
100706   105500    1055  University of Alabama in Huntsville  Huntsville
100724   100500    1005             Alabama State University  Montgomery

In [18]:
ugds = college_race['OPEID'].dropna()
ugds.head()

UNITID
100654     100200
100663     105200
100690    2503400
100706     105500
100724     100500
Name: OPEID, dtype: int64

In [23]:
 df.groupby('CITY')['PREDDEG'].agg('max').head()

CITY
ARTESIA     1
Aberdeen    3
Abilene     3
Abingdon    1
Abington    3
Name: PREDDEG, dtype: int64

In [26]:
df.groupby('CITY').agg({'HCM2': 'max','PREDDEG': 'min'}).head()

          HCM2  PREDDEG
SATMTMID
355.0        0        1
360.0        0        3
365.0        0        3
370.0        0        2
375.0        0        2

In [33]:
agg_dict = {'SATMTMID': ['min', 'max'],
                'SATVRMID': ['min', 'max'],
                'UGDS': 'mean'}
df2 = df.groupby(['STABBR', 'RELAFFIL']).agg(agg_dict)
df2.head(10).round(0)

                SATMTMID        SATVRMID           UGDS
                     min    max      min    max    mean
STABBR RELAFFIL
AK     37.0          NaN    NaN      NaN    NaN    79.0
       71.0          NaN    NaN      NaN    NaN   262.0
       88.0          NaN    NaN      NaN    NaN    33.0
AL     30.0        545.0  545.0    550.0  550.0  1379.0
       42.0          NaN    NaN      NaN    NaN   119.0
       54.0        531.0  559.0    570.0  581.0  1272.0
       55.0          NaN    NaN      NaN    NaN  1820.0
       66.0        420.0  420.0    405.0  405.0   628.0
       68.0          NaN    NaN      NaN    NaN   340.0
       71.0        475.0  530.0    473.0  555.0  1214.0

In [34]:
df2.columns = ['min satmtmid', 'max satmtmid', 'min satvrmid',         
                   'max satvrmid', 'mean ugds']
df2.head()

                 min satmtmid  max satmtmid  min satvrmid  max satvrmid  \
STABBR RELAFFIL
AK     37.0               NaN           NaN           NaN           NaN
       71.0               NaN           NaN           NaN           NaN
       88.0               NaN           NaN           NaN           NaN
AL     30.0             545.0         545.0         550.0         550.0
       42.0               NaN           NaN           NaN           NaN

                 mean ugds
STABBR RELAFFIL
AK     37.0           79.0
       71.0          262.0
       88.0           33.0
AL     30.0         1379.0
       42.0          119.0

In [35]:
df2.reset_index().head()

,STABBR,RELAFFIL,min satmtmid,max satmtmid,min satvrmid,max satvrmid,mean ugds
0,AK,37.0,NaN,NaN,NaN,NaN,79.0
1,AK,71.0,NaN,NaN,NaN,NaN,262.0
2,AK,88.0,NaN,NaN,NaN,NaN,33.0
3,AL,30.0,545.0,545.0,550.0,550.0,1379.0
4,AL,42.0,NaN,NaN,NaN,NaN,119.0

In [36]:
df.columns

Index(['OPEID', 'OPEID6', 'INSTNM', 'CITY', 'STABBR', 'INSTURL', 'NPCURL',
       'HCM2', 'PREDDEG', 'HIGHDEG',
       ...
       'PCTFLOAN', 'UG25ABV', 'MD_EARN_WNE_P10', 'GT_25K_P6', 'GT_28K_P6',
       'GRAD_DEBT_MDN_SUPP', 'GRAD_DEBT_MDN10YR_SUPP', 'RPY_3YR_RT_SUPP',
       'C150_L4_POOLED_SUPP', 'C150_4_POOLED_SUPP'],
      dtype='object', length=123)

In [39]:
columns=df2.columns

In [40]:
columns

Index(['min satmtmid', 'max satmtmid', 'min satvrmid', 'max satvrmid',
       'mean ugds'],
      dtype='object')

In [41]:
type(columns)

pandas.core.indexes.base.Index

In [42]:
df2[['min satmtmid', 'max satmtmid', 'min satvrmid', 'max satvrmid',
       'mean ugds']]

                 min satmtmid  max satmtmid  min satvrmid  max satvrmid  \
STABBR RELAFFIL
AK     37.0               NaN           NaN           NaN           NaN
       71.0               NaN           NaN           NaN           NaN
       88.0               NaN           NaN           NaN           NaN
AL     30.0             545.0         545.0         550.0         550.0
       42.0               NaN           NaN           NaN           NaN
       54.0             531.0         559.0         570.0         581.0
       55.0               NaN           NaN           NaN           NaN
       66.0             420.0         420.0         405.0         405.0
       68.0               NaN           NaN           NaN           NaN
       71.0             475.0         530.0         473.0         555.0
       74.0             500.0         500.0         500.0         500.0
       75.0             500.0         500.0         485.0         485.0
       76.0               NaN           NaN           NaN           NaN
       95.0             425.0         425.0         455.0         455.0
AR     42.0             423.0         423.0         423.0         423.0
       51.0               NaN           NaN           NaN           NaN
       54.0             453.0         453.0         438.0         438.0
       66.0             480.0         535.0         445.0         498.0
       71.0             610.0         610.0         620.0         620.0
       74.0             545.0         545.0         555.0         555.0
       75.0             535.0         535.0         540.0         540.0
AZ     42.0               NaN           NaN           NaN           NaN
       52.0               NaN           NaN           NaN           NaN
       54.0               NaN           NaN           NaN           NaN
       88.0             500.0         500.0         474.0         474.0
CA     27.0             455.0         455.0         475.0         475.0
       30.0             455.0         665.0         446.0         655.0
       34.0             485.0         485.0         498.0         498.0
       39.0             555.0         555.0         542.0         542.0
       41.0               NaN           NaN           NaN           NaN
...                       ...           ...           ...           ...
VA     69.0             515.0         515.0         515.0         515.0
       71.0             435.0         538.0         430.0         545.0
       79.0               NaN           NaN           NaN           NaN
       102.0            530.0         530.0         540.0         540.0
VT     30.0               NaN           NaN           NaN           NaN
       71.0               NaN           NaN           NaN           NaN
WA     27.0             520.0         520.0         539.0         539.0
       30.0             515.0         605.0         508.0         600.0
       39.0             555.0         555.0         550.0         550.0
       64.0             550.0         550.0         560.0         560.0
       79.0               NaN           NaN           NaN           NaN
       95.0             535.0         535.0         530.0         530.0
       103.0            560.0         560.0         570.0         570.0
WI     30.0             460.0         580.0         460.0         575.0
       33.0             590.0         590.0         545.0         545.0
       39.0             505.0         505.0         525.0         525.0
       42.0               NaN           NaN           NaN           NaN
       52.0               NaN           NaN           NaN           NaN
       54.0               NaN           NaN           NaN           NaN
       66.0             510.0         510.0         539.0         539.0
       68.0               NaN           NaN           NaN           NaN
       76.0             465.0         465.0         440.0         440.0
       79.0               NaN           NaN           NaN           NaN
WV     30.0             495.0         495.0         480.0         480.0
       52.0             480.0         480.0         470.0         470.0
       54.0             404.0         404.0         518.0         518.0
       61.0             440.0         440.0         440.0         440.0
       66.0             485.0         485.0         475.0         475.0
       71.0             505.0         505.0         490.0         490.0
       74.0             505.0         505.0         450.0         450.0

                    mean ugds
STABBR RELAFFIL
AK     37.0         79.000000
       71.0        262.000000
       88.0         33.000000
AL     30.0       1379.000000
       42.0        119.000000
       54.0       1272.000000
       55.0       1820.000000
       66.0        628.000000
       68.0        340.000000
       71.0       1214.500000
       74.0        880.000000
       75.0       1367.000000
       76.0        669.000000
       95.0       1719.000000
AR     42.0        265.000000
       51.0        446.000000
       54.0        756.666667
       66.0        677.500000
       71.0       1039.500000
       74.0       2287.000000
       75.0        955.500000
AZ     42.0               NaN
       52.0        293.000000
       54.0         63.000000
       88.0        684.000000
CA     27.0        830.666667
       30.0       2947.727273
       34.0        788.000000
       39.0       2887.000000
       41.0         18.000000
...                       ...
VA     69.0       1233.000000
       71.0       1300.000000
       79.0         61.000000
       102.0     46680.000000
VT     30.0       1043.000000
       71.0        492.000000
WA     27.0        755.000000
       30.0       3644.666667
       39.0       2741.000000
       64.0       3079.000000
       79.0        212.000000
       95.0       1679.000000
       103.0      1294.500000
WI     30.0       2114.777778
       33.0        989.000000
       39.0       2805.000000
       42.0         62.000000
       52.0        160.000000
       54.0        757.000000
       66.0       2911.000000
       68.0       3614.000000
       76.0       1269.500000
       79.0               NaN
WV     30.0        501.500000
       52.0        972.000000
       54.0        160.000000
       61.0        633.000000
       66.0        784.000000
       71.0       1382.000000
       74.0        402.000000

[433 rows x 5 columns]

In [48]:
df2.loc[['AK','AL']]

                 min satmtmid  max satmtmid  min satvrmid  max satvrmid  \
STABBR RELAFFIL
AK     37.0               NaN           NaN           NaN           NaN
       71.0               NaN           NaN           NaN           NaN
       88.0               NaN           NaN           NaN           NaN
AL     30.0             545.0         545.0         550.0         550.0
       42.0               NaN           NaN           NaN           NaN
       54.0             531.0         559.0         570.0         581.0
       55.0               NaN           NaN           NaN           NaN
       66.0             420.0         420.0         405.0         405.0
       68.0               NaN           NaN           NaN           NaN
       71.0             475.0         530.0         473.0         555.0
       74.0             500.0         500.0         500.0         500.0
       75.0             500.0         500.0         485.0         485.0
       76.0               NaN           NaN           NaN           NaN
       95.0             425.0         425.0         455.0         455.0

                 mean ugds
STABBR RELAFFIL
AK     37.0           79.0
       71.0          262.0
       88.0           33.0
AL     30.0         1379.0
       42.0          119.0
       54.0         1272.0
       55.0         1820.0
       66.0          628.0
       68.0          340.0
       71.0         1214.5
       74.0          880.0
       75.0         1367.0
       76.0          669.0
       95.0         1719.0

In [49]:
df.head()

,OPEID,OPEID6,INSTNM,CITY,STABBR,INSTURL,NPCURL,HCM2,PREDDEG,HIGHDEG,...,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GT_25K_P6,GT_28K_P6,GRAD_DEBT_MDN_SUPP,GRAD_DEBT_MDN10YR_SUPP,RPY_3YR_RT_SUPP,C150_L4_POOLED_SUPP,C150_4_POOLED_SUPP
UNITID,,,,,,,,,,,,,,,,,,,,,
100654,100200,1002,Alabama A & M University,Normal,AL,www.aamu.edu/,www2.aamu.edu/scripts/netpricecalc/npcalc.htm,0,3,4,...,0.7667,0.0859,31000,0.453,0.431,32750,348.16551225731,0.2531554273,NaN,0.2913
100663,105200,1052,University of Alabama at Birmingham,Birmingham,AL,www.uab.edu,uab.studentaidcalculator.com/survey.aspx,0,3,4,...,0.5179,0.2363,41200,0.669,0.631,21833,232.106797835537,0.513963161,NaN,0.5384
100690,2503400,25034,Amridge University,Montgomery,AL,www.amridgeuniversity.edu,www2.amridgeuniversity.edu:9091/,0,3,4,...,0.8436,0.8571,39600,0.658,0.542,22890,243.343773299842,0.2307692308,NaN,PrivacySuppressed
100706,105500,1055,University of Alabama in Huntsville,Huntsville,AL,www.uah.edu,finaid.uah.edu/,0,3,4,...,0.4312,0.2255,46700,0.685,0.649,22647,240.760438353933,0.5485090298,NaN,0.4905
100724,100500,1005,Alabama State University,Montgomery,AL,www.alasu.edu,www.alasu.edu/cost-aid/forms/calculator/index....,0,3,4,...,0.8113,0.0974,27700,0.393,0.351,31500,334.876752247489,0.2185867473,NaN,0.2475

In [57]:
df.loc[[100654,100690], ['CITY', 'STABBR', 'INSTNM']]

              CITY STABBR                    INSTNM
UNITID
100654      Normal     AL  Alabama A & M University
100690  Montgomery     AL        Amridge University

In [58]:
df.loc[[100654,100690], :]

,OPEID,OPEID6,INSTNM,CITY,STABBR,INSTURL,NPCURL,HCM2,PREDDEG,HIGHDEG,...,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GT_25K_P6,GT_28K_P6,GRAD_DEBT_MDN_SUPP,GRAD_DEBT_MDN10YR_SUPP,RPY_3YR_RT_SUPP,C150_L4_POOLED_SUPP,C150_4_POOLED_SUPP
UNITID,,,,,,,,,,,,,,,,,,,,,
100654,100200,1002,Alabama A & M University,Normal,AL,www.aamu.edu/,www2.aamu.edu/scripts/netpricecalc/npcalc.htm,0,3,4,...,0.7667,0.0859,31000,0.453,0.431,32750,348.16551225731,0.2531554273,NaN,0.2913
100690,2503400,25034,Amridge University,Montgomery,AL,www.amridgeuniversity.edu,www2.amridgeuniversity.edu:9091/,0,3,4,...,0.8436,0.8571,39600,0.658,0.542,22890,243.343773299842,0.2307692308,NaN,PrivacySuppressed

In [60]:
df2_idx = df.set_index('CITY')

In [61]:
df2_idx.head(10)

,OPEID,OPEID6,INSTNM,STABBR,INSTURL,NPCURL,HCM2,PREDDEG,HIGHDEG,CONTROL,...,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GT_25K_P6,GT_28K_P6,GRAD_DEBT_MDN_SUPP,GRAD_DEBT_MDN10YR_SUPP,RPY_3YR_RT_SUPP,C150_L4_POOLED_SUPP,C150_4_POOLED_SUPP
CITY,,,,,,,,,,,,,,,,,,,,,
Normal,100200,1002,Alabama A & M University,AL,www.aamu.edu/,www2.aamu.edu/scripts/netpricecalc/npcalc.htm,0,3,4,1,...,0.7667,0.0859,31000,0.453,0.431,32750,348.16551225731,0.2531554273,NaN,0.2913
Birmingham,105200,1052,University of Alabama at Birmingham,AL,www.uab.edu,uab.studentaidcalculator.com/survey.aspx,0,3,4,1,...,0.5179,0.2363,41200,0.669,0.631,21833,232.106797835537,0.513963161,NaN,0.5384
Montgomery,2503400,25034,Amridge University,AL,www.amridgeuniversity.edu,www2.amridgeuniversity.edu:9091/,0,3,4,2,...,0.8436,0.8571,39600,0.658,0.542,22890,243.343773299842,0.2307692308,NaN,PrivacySuppressed
Huntsville,105500,1055,University of Alabama in Huntsville,AL,www.uah.edu,finaid.uah.edu/,0,3,4,1,...,0.4312,0.2255,46700,0.685,0.649,22647,240.760438353933,0.5485090298,NaN,0.4905
Montgomery,100500,1005,Alabama State University,AL,www.alasu.edu,www.alasu.edu/cost-aid/forms/calculator/index....,0,3,4,1,...,0.8113,0.0974,27700,0.393,0.351,31500,334.876752247489,0.2185867473,NaN,0.2475
Tuscaloosa,105100,1051,The University of Alabama,AL,www.ua.edu/,financialaid.ua.edu/net-price-calculator/,0,3,4,1,...,0.4007,0.0810,44500,0.695,0.679,23290,247.596176502985,0.6019442985,NaN,0.6793
Alexander City,100700,1007,Central Alabama Community College,AL,www.cacc.edu,www.cacc.edu/NetPriceCalculator/14-15/npcalc.html,0,2,2,1,...,0.3234,0.2630,27700,0.466,0.395,9500,100.994576074639,0.2510056315,0.2136,NaN
Athens,100800,1008,Athens State University,AL,www.athens.edu,https://24.athens.edu/apex/prod8/f?p=174:1:394...,0,3,3,1,...,0.6455,0.6774,38700,0.653,0.612,18000,191.358144141422,0.5038167939,NaN,NaN
Montgomery,831000,8310,Auburn University at Montgomery,AL,www.aum.edu,www.aum.edu/current-students/financial-informa...,0,3,4,1,...,0.5565,0.2257,33300,0.616,0.546,23363,248.372240087558,0.4418886199,NaN,0.2207
Auburn,100900,1009,Auburn University,AL,www.auburn.edu,https://www.auburn.edu/admissions/netpricecalc...,0,3,4,1,...,0.3280,0.0427,48800,0.741,0.726,21500,228.566672168921,0.7239612977,NaN,0.74

In [69]:
df.rename(columns={'CITY': 'citylatest', 'HCM2': 'HCM3'}, inplace=True)

In [70]:
df.head()

,OPEID,OPEID6,INSTNM,citylatest,STABBR,INSTURL,NPCURL,HCM3,PREDDEG,HIGHDEG,...,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GT_25K_P6,GT_28K_P6,GRAD_DEBT_MDN_SUPP,GRAD_DEBT_MDN10YR_SUPP,RPY_3YR_RT_SUPP,C150_L4_POOLED_SUPP,C150_4_POOLED_SUPP
UNITID,,,,,,,,,,,,,,,,,,,,,
100654,100200,1002,Alabama A & M University,Normal,AL,www.aamu.edu/,www2.aamu.edu/scripts/netpricecalc/npcalc.htm,0,3,4,...,0.7667,0.0859,31000,0.453,0.431,32750,348.16551225731,0.2531554273,NaN,0.2913
100663,105200,1052,University of Alabama at Birmingham,Birmingham,AL,www.uab.edu,uab.studentaidcalculator.com/survey.aspx,0,3,4,...,0.5179,0.2363,41200,0.669,0.631,21833,232.106797835537,0.513963161,NaN,0.5384
100690,2503400,25034,Amridge University,Montgomery,AL,www.amridgeuniversity.edu,www2.amridgeuniversity.edu:9091/,0,3,4,...,0.8436,0.8571,39600,0.658,0.542,22890,243.343773299842,0.2307692308,NaN,PrivacySuppressed
100706,105500,1055,University of Alabama in Huntsville,Huntsville,AL,www.uah.edu,finaid.uah.edu/,0,3,4,...,0.4312,0.2255,46700,0.685,0.649,22647,240.760438353933,0.5485090298,NaN,0.4905
100724,100500,1005,Alabama State University,Montgomery,AL,www.alasu.edu,www.alasu.edu/cost-aid/forms/calculator/index....,0,3,4,...,0.8113,0.0974,27700,0.393,0.351,31500,334.876752247489,0.2185867473,NaN,0.2475

In [71]:
df.sort_values(by=['citylatest', 'STABBR'])

,OPEID,OPEID6,INSTNM,citylatest,STABBR,INSTURL,NPCURL,HCM3,PREDDEG,HIGHDEG,...,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GT_25K_P6,GT_28K_P6,GRAD_DEBT_MDN_SUPP,GRAD_DEBT_MDN10YR_SUPP,RPY_3YR_RT_SUPP,C150_L4_POOLED_SUPP,C150_4_POOLED_SUPP
UNITID,,,,,,,,,,,,,,,,,,,,,
457314,4164400,41644,Angeles Institute,ARTESIA,CA,www.angelesinstitute.edu/,angelesinstitutenetpricecalc.com/index.html,0,1,1,...,0.0685,0.4844,PrivacySuppressed,NaN,PrivacySuppressed,16850,179.132484932387,0.4238683128,0.5701,NaN
219259,346600,3466,Northern State University,Aberdeen,SD,www.northern.edu,www.northern.edu/net-price-calculator,0,3,4,...,0.3424,0.1414,35300,0.702,0.623,25250,268.432952198384,0.6467486819,NaN,0.4519
219295,346700,3467,Presentation College,Aberdeen,SD,www.presentation.edu,www.presentation.edu/tuition-aid/net-price-cal...,0,3,3,...,0.7672,0.4031,34700,0.688,0.663,26000,276.406208204277,0.5949367089,NaN,0.4132
235334,377900,3779,Grays Harbor College,Aberdeen,WA,www.ghc.edu,www.ghc.edu/content/net-price-calculator,0,1,2,...,0.1563,0.4385,27800,0.431,0.373,9500,100.994576074639,0.314893617,NaN,0.3736
222178,353700,3537,Abilene Christian University,Abilene,TX,www.acu.edu,www.acu.edu/campusoffices/sfs/calculator/fresh...,0,3,4,...,0.5237,0.0218,43000,0.687,0.661,23628,251.18945720964,0.7013401404,NaN,0.6161
225247,357100,3571,Hardin-Simmons University,Abilene,TX,www.hsutx.edu,www.hsutx.edu/offices/financial-aid/financial-...,0,3,4,...,0.5827,0.1002,43300,0.738,0.688,26000,276.406208204277,0.6398779247,NaN,0.5253
226587,359100,3591,McMurry University,Abilene,TX,ww2.mcm.edu,financial-aid.mcm.edu/calculators/index.html,0,3,4,...,0.8326,0.1721,41000,0.645,0.618,28000,297.66822421999,0.5298245614,NaN,0.3567
377315,3025000,30250,Texas College of Cosmetology-Abilene,Abilene,TX,www.texascollegecosmetology.com,www.texascollegecosmetology.com,0,1,1,...,0.0000,0.2923,16700,0.204,0.116,PrivacySuppressed,PrivacySuppressed,NaN,0.7282,NaN
483513,4231200,42312,NeeCee's College of Cosmetology,Abilene,TX,neeceescollege.com,neeceescollege.com,0,1,1,...,0.7917,0.5106,NaN,NaN,NaN,PrivacySuppressed,PrivacySuppressed,NaN,0.5814,NaN
233903,709900,7099,Virginia Highlands Community College,Abingdon,VA,www.vhcc.edu,https://www.vawizard.org/vccs/FinAidCostCompar...,0,1,2,...,0.0000,0.2444,25500,0.414,0.373,PrivacySuppressed,PrivacySuppressed,NaN,0.3156,NaN
214801,332913,3329,Pennsylvania State University-Penn State Abington,Abington,PA,abington.psu.edu/,tuition.psu.edu/CostEstimate.aspx,0,3,4,...,0.5552,0.1987,50100,0.731,0.702,26120,277.68192916522,0.6791956399,NaN,0.4761
204635,308900,3089,Ohio Northern University,Ada,OH,www.onu.edu/,https://tcc.noellevitz.com/(S(44tm4xji3okjqs55...,0,3,4,...,0.7763,0.0262,63500,0.828,0.83,27000,287.037216212134,0.8451290591,NaN,0.7348
206905,2597400,25974,Pontotoc Technology Center,Ada,OK,www.pontotoctech.edu,www.pontotoctech.edu,0,1,1,...,0.0000,0.4563,27500,0.5,0.429,PrivacySuppressed,PrivacySuppressed,NaN,0.94,NaN
207041,315400,3154,East Central University,Ada,OK,https://www.ecok.edu,https://www.ecok.edu/netprice/npcalc.htm,0,3,4,...,0.3677,0.2012,36800,0.629,0.563,16687.5,177.40494613111,0.4799068142,NaN,0.3482
454227,638500,6385,Chamberlain University-Illinois,Addison,IL,www.chamberlain.edu,www.chamberlain.edu/admissions/financial-aid-s...,0,3,4,...,0.6564,0.8869,58400,0.912,0.902,22893.5,243.38098182787,0.595370464,NaN,PrivacySuppressed
485874,4249300,42493,Salon Boutique Academy,Addison,TX,www.salonboutiqueacademy.com,www.salonboutiqueacademy.com/finance.html,0,1,1,...,0.3554,NaN,NaN,NaN,NaN,7415.5,78.8342398822622,NaN,0.7821,NaN
163204,1164400,11644,University of Maryland-University College,Adelphi,MD,www.umuc.edu,www.umuc.edu/students/aid/applyforaid/netprice...,0,3,4,...,0.2438,0.7884,51200,0.716,0.707,18215,193.643810863111,0.4313363244,NaN,0.09
186900,1198900,11989,Talmudical Academy-New Jersey,Adelphia,NJ,talmudicalacademynj.com,https://sites.google.com/site/talmudicalacadem...,0,3,3,...,0.0000,0.0303,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,NaN,NaN,PrivacySuppressed
168528,223400,2234,Adrian College,Adrian,MI,www.adrian.edu,adrian.edu/admissions/financial-aid/financial-...,0,3,4,...,0.8773,0.0124,38600,0.629,0.591,27000,287.037216212134,0.6191425723,NaN,0.5333
172264,231600,2316,Siena Heights University,Adrian,MI,www.sienaheights.edu,sienaheights.edu/FinancialAid/NetPriceCalculat...,0,3,4,...,0.6409,0.4775,42000,0.707,0.688,17250,183.38488813553,0.5288350634,NaN,0.4175
420459,2052702,20527,Northeast Technology Center-Afton,Afton,OK,www.netech.edu,www.netech.edu,0,1,1,...,0.0000,0.0864,28400,0.595,0.462,PrivacySuppressed,PrivacySuppressed,NaN,0.6364,NaN
418755,3061900,30619,Colegio Tecnologico y Comercial de Puerto Rico,Aguada,PR,ctcpr.edu,ctcpr.edu,0,1,1,...,0.0000,0.4095,14700,0.167,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,NaN,0.4295,NaN
445498,3800300,38003,Colegio Tecnico de Electricidad Galloza,Aguada,PR,www.ctegpr.com/CTEG_Web/,www.ctegpr.com/Principal/npcalc.htm,0,1,1,...,0.0000,0.5370,PrivacySuppressed,0.161,0.216,PrivacySuppressed,PrivacySuppressed,NaN,0.8704,NaN
446516,3638300,36383,Rosslyn Training Academy of Cosmetology,Aguada,PR,rosslyntrainig.edu,www.rosslyntraining.edu/calculadora.html,0,1,1,...,0.0000,0.3462,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,NaN,0.6,NaN
242626,393900,3939,Inter American University of Puerto Rico-Aguad...,Aguadilla,PR,www.aguadilla.inter.edu,aguadilla.inter.edu/servicios/netprice/npcalc.htm,0,3,4,...,0.2260,0.2104,19800,0.233,0.218,5500,58.4705440432125,PrivacySuppressed,NaN,0.3028
243106,1212300,12123,University of Puerto Rico-Aguadilla,Aguadilla,PR,https://www.uprag.edu,https://www.uprag.edu/index.php?page=enlaces-2,0,3,3,...,0.1308,0.0627,PrivacySuppressed,NaN,PrivacySuppressed,5500,58.4705440432125,0.5598591549,NaN,0.3794
376385,3029700,30297,Universal Technology College of Puerto Rico,Aguadilla,PR,www.unitecpr.edu,nces.ed.gov/ipeds/netpricecalculator/,0,1,3,...,0.0000,0.3877,17000,0.176,0.155,PrivacySuppressed,PrivacySuppressed,NaN,NaN,0.6123
418782,2297702,22977,Automeca Technical College-Aguadilla,Aguadilla,PR,www.automeca.com,www.automeca.com,0,1,1,...,0.3191,0.2298,19300,0.192,0.159,2800,29.766822421999,0.3635097493,0.6511,NaN
443951,3735400,37354,Charlie's Guard-Detective Bureau and Academy Inc,Aguadilla,PR,www.charliesacademy.edu,www.charliesacademy.edu/netprice_calculator/np...,0,1,1,...,0.0000,0.4923,PrivacySuppressed,0.064,0.109,PrivacySuppressed,PrivacySuppressed,NaN,0.6522,NaN
445984,3849300,38493,Xtreme Career Institute,Aguadilla,PR,www.xtreme-career.com,calculator.xtreme-career.com/,0,1,1,...,0.0000,0.3661,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,NaN,0.5093,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190071,644300,6443,Cochran School of Nursing,Yonkers,NY,www.cochranschoolofnursing.us,www.cochranschoolofnursing.us/Admissions/Summa...,0,2,2,...,0.7978,0.7978,84000,0.924,0.863,20000,212.620160157136,0.5916666667,NaN,NaN
195580,283300,2833,Saint Vladimirs Orthodox Theological Seminary,Yonkers,NY,www.svots.edu,www.svots.edu,0,4,4,...,NaN,NaN,NaN,NaN,NaN,PrivacySuppressed,PrivacySuppressed,NaN,NaN,NaN
181853,256700,2567,York College,York,NE,www.york.edu/,www.york.edu/Admissions-Aid/Financial-Services...,0,3,4,...,0.7698,0.0149,35400,0.494,0.51,26000,276.406208204277,0.5907590759,NaN,0.4575
210906,2557800,25578,The Art Institutes of York-PA,York,PA,www.artinstitutes.edu/york,tcc.noellevitz.com/edmc/Freshman-Students Net ...,0,3,3,...,0.7696,0.1935,33300,0.507,0.415,27000,287.037216212134,0.4585635359,NaN,0.5331
211820,2289600,22896,Consolidated School of Business-York,York,PA,www.csb.edu,www.csb.edu,0,2,2,...,0.7931,0.5692,26600,0.467,0.311,14205,151.013468751606,0.2836879433,0.6143,NaN
212267,1054205,10542,Empire Beauty School-York,York,PA,www.empire.edu,www.empire.edu/net-price-calculator,0,1,1,...,0.7458,0.4685,18500,0.231,0.209,11526,122.532998298557,0.2978723404,0.4836,NaN
214829,332918,3329,Pennsylvania State University-Penn State York,York,PA,york.psu.edu/,tuition.psu.edu/CostEstimate.aspx,0,3,3,...,0.4977,0.1647,50100,0.731,0.702,26120,277.68192916522,0.6791956399,NaN,0.5041
217059,339900,3399,York College of Pennsylvania,York,PA,www.ycp.edu,https://tcc.noellevitz.com/(S(3frm42zkl0tip1yc...,0,3,4,...,0.6858,0.0745,50400,0.748,0.715,26436.5,281.046643199706,0.7264815582,NaN,0.5867
217077,2127400,21274,YTI Career Institute-York,York,PA,www.yti.edu,www.yti.edu,0,2,2,...,0.7429,0.2759,36300,0.567,0.519,13000,138.203104102138,0.4515701017,0.6643,NaN
418409,536500,5365,York County School of Technology-Adult & Conti...,York,PA,www.ytech.edu,www.ytech.edu/UserFiles/Servers/Server_2032623...,0,1,1,...,0.1064,0.5681,37300,0.736,0.725,9500,100.994576074639,0.5892857143,0.5747,NaN
469586,3296301,32963,Baltimore School of Massage-York,York,PA,www.steinered.com/,www.bsmyork.com/npcalc_york.htm,0,1,1,...,0.9484,0.6226,29400,0.461,0.404,7917,84.1656903982024,0.351782364,0.6151,NaN
21287804,327348,3273,Harrisburg Area Community College-York,York,PA,www.hacc.edu/,NaN,0,0,0,...,NaN,NaN,34900,0.562,0.521,18228,193.782013967214,0.4193191049,NaN,NaN
431770,1095200,10952,Putnam Westchester BOCES-Practical Nursing Pro...,Yorktown Heights,NY,www.pnwboces.org,www.pnwboces.org/adulted/NPCALC/npcalc.htm,0,1,1,...,0.6250,0.6667,56900,0.902,0.864,PrivacySuppressed,PrivacySuppressed,0.5853658537,0.8235,NaN
141361,160400,1604,Young Harris College,Young Harris,GA,www.yhc.edu,www.yhc.edu/admissions/financial-aid/calculator,0,3,3,...,0.6063,0.0174,37900,0.518,0.491,26400,280.65861140742,0.5885714286,NaN,0.488
201803,747300,7473,Choffin Career and Technical Center,Youngstown,OH,www.choffincareer.com,www.youngstown.k12.oh.us/NetPriceCalculator.aspx,0,1,1,...,0.7479,0.5882,28900,0.591,0.471,6500,69.1015520510693,0.4609375,0.8732,NaN
206695,314500,3145,Youngstown State University,Youngstown,OH,www.ysu.edu,cfweb.cc.ysu.edu/finaid/estimator/est_estimato...,0,3,4,...,0.5890,0.2058,35900,0.557,0.511,26495.5,281.67387267217,0.3928376162,NaN,0.304
453464,372611,3726,American National University-Youngstown,Youngstown,OH,https://www.an.edu/locations/youngstown-oh/,https://www.an.edu/admissions/financial-assist...,0,2,2,...,0.6100,0.7400,21000,0.296,0.232,24667,262.235074529804,0.1601953602,0.3549,NaN
216825,1017600,10176,Westmoreland County Community College,Youngwood,PA,https://westmoreland.edu,https://westmoreland.edu/NetPriceCalculator/np...,0,2,2,...,0.5728,0.3205,31800,0.497,0.462,PrivacySuppressed,PrivacySuppressed,0.4655775963,0.1355,NaN
169798,225900,2259,Eastern Michigan University,Ypsilanti,MI,www.emich.edu,www.emich.edu/finaid/calculator/,0,3,4,...,0.6957,0.2293,39300,0.616,0.579,25270,268.645572358541,0.438433589,NaN,0.4037
446093,3874300,38743,Cambridge Junior College-Yuba City,Yuba City,CA,www.cambridge.edu,www.cambridge.edu/npc/npcalc.htm,0,1,2,...,0.5789,0.3372,PrivacySuppressed,0.289,0.3,9500,100.994576074639,0.3296703297,0.7285,NaN
483610,4190900,41909,Sutter Beauty College,Yuba City,CA,sutterbeautycollege.com,sutterbeautycollege.comcastbiz.net/net-price-c...,0,1,1,...,0.0000,0.2763,NaN,NaN,NaN,PrivacySuppressed,PrivacySuppressed,NaN,0.6538,NaN
113111,927200,9272,Crafton Hills College,Yucaipa,CA,www.craftonhills.edu,https://nces.ed.gov/ipeds/netpricecalculator/N...,0,2,2,...,0.0000,0.2946,33000,0.507,0.434,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,0.2914,NaN
461607,4175400,41754,Elite Cosmetology School,Yucca Valley,CA,eliteschools.edu,eliteschools.edu/net-price-calculator/,0,1,1,...,0.5271,0.2917,NaN,NaN,NaN,8492,90.2785200027201,0.3243243243,0.6528,NaN
413820,2556500,25565,Yukon Beauty College Inc,Yukon,OK,www.yukonbeautycollege.com,www.yukonbeautycollege.com,0,1,1,...,0.5429,0.4211,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,0.75,NaN
104160,107100,1071,Arizona Western College,Yuma,AZ,www.azwestern.edu,schedule.azwestern.edu/npcalc/npcalc.html,0,1,2,...,0.0329,0.2976,27700,0.406,0.356,4925,52.3577144386948,0.3570451436,0.1681,NaN
487889,4237700,42377,Regional Center for Border Health,Yuma,AZ,www.rcbh.edu/index.html,www.nces.ed.gov/ipeds/netpricecalculator,0,1,1,...,0.0053,NaN,NaN,NaN,NaN,PrivacySuppressed,PrivacySuppressed,NaN,NaN,NaN
204255,813300,8133,Zane State College,Zanesville,OH,www.zanestate.edu,https://my.zanestate.edu/ICS/Finances/Net_Pric...,0,2,2,...,0.2320,0.2829,29800,0.415,0.371,8834,93.9143247414071,0.2937671861,0.3099,NaN
204866,310002,3100,Ohio University-Zanesville Campus,Zanesville,OH,www.zanesville.ohiou.edu/,www.ohio.edu/financialaid/regionalcalculator/,0,2,2,...,0.3964,0.2503,40500,0.63,0.596,20072,213.385592733702,0.5229866104,NaN,0.2786
389860,2189000,21890,Mid-EastCTC-Adult Education,Zanesville,OH,www.mideastadulted.org,www.mideastadulted.org,0,1,1,...,0.8216,0.4892,30700,0.508,0.512,7600,80.7956608597118,0.3701492537,0.7868,NaN
475404,4190500,41905,New York School of Esthetics & Day Spa,white plains,NY,www.newyorkschoolofesthetics.com,www.newyorkschoolofesthetics.com,0,1,1,...,0.3500,0.6818,NaN,NaN,NaN,PrivacySuppressed,PrivacySuppressed,0.6666666667,0.9333,NaN

In [72]:
df['STABBR'].unique()

array(['AL', 'IL', 'AK', 'WA', 'AZ', 'NM', 'AR', 'CA', 'MN', 'CO', 'CT',
       'NY', 'DE', 'DC', 'FL', 'GA', 'HI', 'ID', 'IN', 'MI', 'IA', 'KS',
       'MO', 'KY', 'LA', 'ME', 'MD', 'MA', 'MS', 'MT', 'NE', 'NV', 'NH',
       'NJ', 'NC', 'ND', 'OH', 'WV', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD',
       'TN', 'TX', 'UT', 'VT', 'VA', 'WI', 'WY', 'AS', 'GU', 'MP', 'PR',
       'FM', 'PW', 'VI', 'MH'], dtype=object)

In [75]:
df['citylatest'].isna().sum()

0

In [76]:
df.isna().any()

OPEID                     False
OPEID6                    False
INSTNM                    False
citylatest                False
STABBR                    False
INSTURL                    True
NPCURL                     True
HCM3                      False
PREDDEG                   False
HIGHDEG                   False
CONTROL                   False
LOCALE                     True
HBCU                       True
PBI                        True
ANNHI                      True
TRIBAL                     True
AANAPII                    True
HSI                        True
NANTI                      True
MENONLY                    True
WOMENONLY                  True
RELAFFIL                   True
SATVR25                    True
SATVR75                    True
SATMT25                    True
SATMT75                    True
SATWR25                    True
SATWR75                    True
SATVRMID                   True
SATMTMID                   True
                          ...
UGDS_UNKN                  True
PPTUG_EF                   True
CURROPER                  False
NPT4_PUB                   True
NPT4_PRIV                  True
NPT41_PUB                  True
NPT42_PUB                  True
NPT43_PUB                  True
NPT44_PUB                  True
NPT45_PUB                  True
NPT41_PRIV                 True
NPT42_PRIV                 True
NPT43_PRIV                 True
NPT44_PRIV                 True
NPT45_PRIV                 True
PCTPELL                    True
RET_FT4_POOLED_SUPP        True
RET_FTL4_POOLED_SUPP       True
RET_PT4_POOLED_SUPP        True
RET_PTL4_POOLED_SUPP       True
PCTFLOAN                   True
UG25ABV                    True
MD_EARN_WNE_P10            True
GT_25K_P6                  True
GT_28K_P6                  True
GRAD_DEBT_MDN_SUPP         True
GRAD_DEBT_MDN10YR_SUPP     True
RPY_3YR_RT_SUPP            True
C150_L4_POOLED_SUPP        True
C150_4_POOLED_SUPP         True
Length: 123, dtype: bool

In [77]:
df.loc[:, df.isna().any()]

,INSTURL,NPCURL,LOCALE,HBCU,PBI,ANNHI,TRIBAL,AANAPII,HSI,NANTI,...,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GT_25K_P6,GT_28K_P6,GRAD_DEBT_MDN_SUPP,GRAD_DEBT_MDN10YR_SUPP,RPY_3YR_RT_SUPP,C150_L4_POOLED_SUPP,C150_4_POOLED_SUPP
UNITID,,,,,,,,,,,,,,,,,,,,,
100654,www.aamu.edu/,www2.aamu.edu/scripts/netpricecalc/npcalc.htm,12.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.7667,0.0859,31000,0.453,0.431,32750,348.16551225731,0.2531554273,NaN,0.2913
100663,www.uab.edu,uab.studentaidcalculator.com/survey.aspx,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.5179,0.2363,41200,0.669,0.631,21833,232.106797835537,0.513963161,NaN,0.5384
100690,www.amridgeuniversity.edu,www2.amridgeuniversity.edu:9091/,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.8436,0.8571,39600,0.658,0.542,22890,243.343773299842,0.2307692308,NaN,PrivacySuppressed
100706,www.uah.edu,finaid.uah.edu/,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.4312,0.2255,46700,0.685,0.649,22647,240.760438353933,0.5485090298,NaN,0.4905
100724,www.alasu.edu,www.alasu.edu/cost-aid/forms/calculator/index....,12.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.8113,0.0974,27700,0.393,0.351,31500,334.876752247489,0.2185867473,NaN,0.2475
100751,www.ua.edu/,financialaid.ua.edu/net-price-calculator/,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.4007,0.0810,44500,0.695,0.679,23290,247.596176502985,0.6019442985,NaN,0.6793
100760,www.cacc.edu,www.cacc.edu/NetPriceCalculator/14-15/npcalc.html,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.3234,0.2630,27700,0.466,0.395,9500,100.994576074639,0.2510056315,0.2136,NaN
100812,www.athens.edu,https://24.athens.edu/apex/prod8/f?p=174:1:394...,31.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.6455,0.6774,38700,0.653,0.612,18000,191.358144141422,0.5038167939,NaN,NaN
100830,www.aum.edu,www.aum.edu/current-students/financial-informa...,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.5565,0.2257,33300,0.616,0.546,23363,248.372240087558,0.4418886199,NaN,0.2207
100858,www.auburn.edu,https://www.auburn.edu/admissions/netpricecalc...,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.3280,0.0427,48800,0.741,0.726,21500,228.566672168921,0.7239612977,NaN,0.74
100937,www.bsc.edu/,www.bsc.edu/fp/np-calculator.cfm,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.4729,0.0141,46700,0.637,0.618,26045,276.88460356463,0.7559912854,NaN,0.6439
101028,www.cv.edu,https://www.cv.edu/about/consumer-information/,41.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.2697,0.3604,28900,0.41,0.35,10500,111.625584082496,0.28125,0.1332,NaN
101073,www.ccal.edu/,www.ccal.edu/admissions/net-pricing-calculator/,32.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.8830,0.1294,20600,0.356,0.307,35000,372.085280274988,0.1565074135,NaN,0.1487
101116,www.southuniversity.edu/montgomery#location=Mo...,tcc.noellevitz.com/edmc/South Net Price Calcul...,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.7087,0.6109,33400,0.58,0.478,25000,265.77520019642,0.2547585843,NaN,0.0714
101143,www.escc.edu,https://www.escc.edu/netprice/npcalc.htm,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.1738,0.2896,31800,0.518,0.484,6676,70.9726094604521,0.4260416667,0.1392,NaN
101161,www.coastalalabama.edu,www.coastalalabama.edu,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.4779,0.2598,29100,0.475,0.41,11000,116.941088086425,0.3489905233,0.1825,NaN
101189,www.faulkner.edu,www.faulkner.edu/net-price-calculator-form/,12.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.6954,0.4353,35400,0.614,0.532,22850,242.918532979528,0.3081623745,NaN,0.2683
101240,www.gadsdenstate.edu,www.gadsdenstate.edu/net-price-calculator,13.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0000,0.3320,26700,0.379,0.349,PrivacySuppressed,PrivacySuppressed,NaN,0.1779,NaN
101277,www.nbccosmetology.com,nbccosmetology.com/sa/nbc_zonemap/,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.4545,0.2747,NaN,NaN,NaN,5900,62.7229472463552,0.4205607477,0.7338,NaN
101286,www.wallace.edu,www.wallace.edu/net_price_calculator.aspx,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0000,0.3422,24700,0.374,0.339,PrivacySuppressed,PrivacySuppressed,NaN,0.2036,NaN
101295,www.wallacestate.edu,www.wallacestate.edu/Financial-Aid/Net-Price-C...,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.3330,0.2671,32200,0.537,0.476,10500,111.625584082496,0.4397394137,0.3637,NaN
101301,www.wccs.edu,www.wccs.edu/financial-aid/net-price-calculator/,32.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0000,0.2753,23300,0.376,0.305,PrivacySuppressed,PrivacySuppressed,NaN,0.1709,NaN
101365,www.herzing.edu/,www.herzing.edu/financial-aid/net-price-calcul...,21.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.7083,0.7147,37800,0.566,0.497,23139.5,245.996209797802,0.3041105434,NaN,0.3111
101435,www.huntingdon.edu,hawk.huntingdon.edu/oiac/netpricecalculator/np...,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.7093,0.2196,39900,0.612,0.573,27000,287.037216212134,0.5146036161,NaN,0.3996
101453,www.hcu.edu,www.hcu.edu/netpricecalculator/,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.2586,0.5862,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,NaN,PrivacySuppressed
101462,www.drakestate.edu,www.drakestate.edu/admissions/net_price_calcul...,12.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0000,0.4769,23800,0.369,0.296,PrivacySuppressed,PrivacySuppressed,NaN,0.1547,NaN
101471,www.istc.edu,nces.ed.gov/ipeds/netpricecalculator/Npc_2.aspx,21.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0000,NaN,NaN,NaN,NaN,PrivacySuppressed,PrivacySuppressed,NaN,0.3739,NaN
101480,www.jsu.edu/,www.jsu.edu/finaid/,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.6435,0.1814,35800,0.548,0.515,23500,249.828688184635,0.4210392257,NaN,0.3329
101499,www.coastalalabama.edu,www.coastalalabama.edu,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0000,0.3843,26200,0.452,0.403,PrivacySuppressed,PrivacySuppressed,NaN,0.2887,NaN
101505,www.jeffersonstate.edu/,www.jeffersonstate.edu/financial-aid/net-price...,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.1784,0.3118,30600,0.534,0.48,7368,78.329267001889,0.4485852312,0.0804,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45897302,www.strayer.edu/texas/katy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,45900,0.667,0.59,34239.5,364.000398685013,0.2382231351,NaN,NaN
45897303,www.strayer.edu/texas/northwest-houston,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,45900,0.667,0.59,34239.5,364.000398685013,0.2382231351,NaN,NaN
45897304,www.strayer.edu/texas/plano,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,45900,0.667,0.59,34239.5,364.000398685013,0.2382231351,NaN,NaN
45897305,www.strayer.edu/texas/cedar-hill,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,45900,0.667,0.59,34239.5,364.000398685013,0.2382231351,NaN,NaN
45897306,www.strayer.edu/texas/north-dallas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,45900,0.667,0.59,34239.5,364.000398685013,0.2382231351,NaN,NaN
45897307,www.strayer.edu/texas/san-antonio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,45900,0.667,0.59,34239.5,364.000398685013,0.2382231351,NaN,NaN
45897308,www.strayer.edu/texas/stafford,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,45900,0.667,0.59,34239.5,364.000398685013,0.2382231351,NaN,NaN
45920401,www.unitekcollege.edu/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,PrivacySuppressed,NaN,PrivacySuppressed,9500,100.994576074639,0.6733556299,NaN,NaN
47503301,relay.edu/location/relay-newark,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,PrivacySuppressed,PrivacySuppressed,NaN,NaN,NaN
47503302,relay.edu/location/relay-new-orleans,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,PrivacySuppressed,PrivacySuppressed,NaN,NaN,NaN
47503303,relay.edu/location/relay-delaware,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,PrivacySuppressed,PrivacySuppressed,NaN,NaN,NaN
47503304,relay.edu/location/relay-memphis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,PrivacySuppressed,PrivacySuppressed,NaN,NaN,NaN
47503305,relay.edu/location/relay-houston,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,PrivacySuppressed,PrivacySuppressed,NaN,NaN,NaN
47503306,relay.edu/location/relay-chicago,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,PrivacySuppressed,PrivacySuppressed,NaN,NaN,NaN
47503307,relay.edu/location/relay-baton-rouge,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,PrivacySuppressed,PrivacySuppressed,NaN,NaN,NaN
47503308,relay.edu/location/relay-philadelphia-camden,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,PrivacySuppressed,PrivacySuppressed,NaN,NaN,NaN
47503309,relay.edu/location/relay-denver,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,PrivacySuppressed,PrivacySuppressed,NaN,NaN,NaN
47503310,relay.edu/location/relay-nashville,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,PrivacySuppressed,PrivacySuppressed,NaN,NaN,NaN
47647001,www.westmedcollege.edu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,10093,107.298763823298,0.5258964143,NaN,NaN
47657701,www.vantage.edu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,9500,100.994576074639,0.2150537634,NaN,NaN
47657702,www.vantage.edu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,9500,100.994576074639,0.2150537634,NaN,NaN
47662901,www.saloninstitute.edu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,12000,127.572096094281,0.4695652174,NaN,NaN
47691101,usa.sae.edu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,9500,100.994576074639,0.4794520548,NaN,NaN
48065701,rasmussen.edu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,32600,0.553,0.491,18254,194.058420175418,0.3513632366,NaN,NaN
48154401,nptiohio.edu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6333,67.3261737137572,PrivacySuppressed,NaN,NaN
48305401,www.bsp.edu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,13583,144.400981770719,PrivacySuppressed,NaN,NaN
48387801,www.bamasf.com/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,8850,94.0844208695328,NaN,NaN,NaN
48400201,www.hdmc.edu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,7521,79.9558112270911,PrivacySuppressed,NaN,NaN
48414501,www.vantage.edu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,9891.5,105.156615709715,NaN,NaN,NaN
48778201,bostoncareer.org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,PrivacySuppressed,PrivacySuppressed,NaN,NaN,NaN

In [79]:
df[df['citylatest'].isnull()]

Empty DataFrame
Columns: [OPEID, OPEID6, INSTNM, citylatest, STABBR, INSTURL, NPCURL, HCM3, PREDDEG, HIGHDEG, CONTROL, LOCALE, HBCU, PBI, ANNHI, TRIBAL, AANAPII, HSI, NANTI, MENONLY, WOMENONLY, RELAFFIL, SATVR25, SATVR75, SATMT25, SATMT75, SATWR25, SATWR75, SATVRMID, SATMTMID, SATWRMID, ACTCM25, ACTCM75, ACTEN25, ACTEN75, ACTMT25, ACTMT75, ACTWR25, ACTWR75, ACTCMMID, ACTENMID, ACTMTMID, ACTWRMID, SAT_AVG, SAT_AVG_ALL, PCIP01, PCIP03, PCIP04, PCIP05, PCIP09, PCIP10, PCIP11, PCIP12, PCIP13, PCIP14, PCIP15, PCIP16, PCIP19, PCIP22, PCIP23, PCIP24, PCIP25, PCIP26, PCIP27, PCIP29, PCIP30, PCIP31, PCIP38, PCIP39, PCIP40, PCIP41, PCIP42, PCIP43, PCIP44, PCIP45, PCIP46, PCIP47, PCIP48, PCIP49, PCIP50, PCIP51, PCIP52, PCIP54, DISTANCEONLY, UGDS, UGDS_WHITE, UGDS_BLACK, UGDS_HISP, UGDS_ASIAN, UGDS_AIAN, UGDS_NHPI, UGDS_2MOR, UGDS_NRA, UGDS_UNKN, PPTUG_EF, CURROPER, NPT4_PUB, NPT4_PRIV, NPT41_PUB, NPT42_PUB, ...]
Index: []

[0 rows x 123 columns]

In [80]:
df.tail(n=2)

,OPEID,OPEID6,INSTNM,citylatest,STABBR,INSTURL,NPCURL,HCM3,PREDDEG,HIGHDEG,...,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GT_25K_P6,GT_28K_P6,GRAD_DEBT_MDN_SUPP,GRAD_DEBT_MDN10YR_SUPP,RPY_3YR_RT_SUPP,C150_L4_POOLED_SUPP,C150_4_POOLED_SUPP
UNITID,,,,,,,,,,,,,,,,,,,,,
48414501,4232401,42324,Vantage College-San Antonio,San Antonio,TX,www.vantage.edu,NaN,0,0,0,...,NaN,NaN,NaN,NaN,NaN,9891.5,105.156615709715,NaN,NaN,NaN
48778201,4221501,42215,BCI - Malden,Malden,MA,bostoncareer.org,NaN,0,0,0,...,NaN,NaN,NaN,NaN,NaN,PrivacySuppressed,PrivacySuppressed,NaN,NaN,NaN

In [83]:
import pyarrow.parquet as pq
df.to_parquet('data.parquet')
df = pq.read_table('data.parquet').to_pandas()

In [84]:
df.head()

,OPEID,OPEID6,INSTNM,citylatest,STABBR,INSTURL,NPCURL,HCM3,PREDDEG,HIGHDEG,...,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GT_25K_P6,GT_28K_P6,GRAD_DEBT_MDN_SUPP,GRAD_DEBT_MDN10YR_SUPP,RPY_3YR_RT_SUPP,C150_L4_POOLED_SUPP,C150_4_POOLED_SUPP
UNITID,,,,,,,,,,,,,,,,,,,,,
100654,100200,1002,Alabama A & M University,Normal,AL,www.aamu.edu/,www2.aamu.edu/scripts/netpricecalc/npcalc.htm,0,3,4,...,0.7667,0.0859,31000,0.453,0.431,32750,348.16551225731,0.2531554273,None,0.2913
100663,105200,1052,University of Alabama at Birmingham,Birmingham,AL,www.uab.edu,uab.studentaidcalculator.com/survey.aspx,0,3,4,...,0.5179,0.2363,41200,0.669,0.631,21833,232.106797835537,0.513963161,None,0.5384
100690,2503400,25034,Amridge University,Montgomery,AL,www.amridgeuniversity.edu,www2.amridgeuniversity.edu:9091/,0,3,4,...,0.8436,0.8571,39600,0.658,0.542,22890,243.343773299842,0.2307692308,None,PrivacySuppressed
100706,105500,1055,University of Alabama in Huntsville,Huntsville,AL,www.uah.edu,finaid.uah.edu/,0,3,4,...,0.4312,0.2255,46700,0.685,0.649,22647,240.760438353933,0.5485090298,None,0.4905
100724,100500,1005,Alabama State University,Montgomery,AL,www.alasu.edu,www.alasu.edu/cost-aid/forms/calculator/index....,0,3,4,...,0.8113,0.0974,27700,0.393,0.351,31500,334.876752247489,0.2185867473,None,0.2475

In [85]:
df.to_csv('file.csv', index=False)